export const products = [
  {
    id: 1,
    name: 'Smartphone Nova X1',
    description: 'Smartphone com tela AMOLED de 6.5", 128GB de armazenamento e câmera tripla de 64MP.',
    price: 2499.9,
    category: 'Eletrônicos',
    stock: 15,
    image: 'https://picsum.photos/seed/smartphone/600/400',
  },
  {
    id: 2,
    name: 'Notebook UltraBook Pro 14',
    description: 'Notebook ultrafino com processador i7, 16GB RAM, SSD 512GB e tela 14" Full HD.',
    price: 5899.0,
    category: 'Eletrônicos',
    stock: 8,
    image: 'https://picsum.photos/seed/notebook/600/400',
  },
  {
    id: 3,
    name: 'Fone de Ouvido SoundMax',
    description: 'Fone Bluetooth com cancelamento ativo de ruído e bateria de 30 horas.',
    price: 499.9,
    category: 'Áudio',
    stock: 30,
    image: 'https://picsum.photos/seed/headphone/600/400',
  },
  {
    id: 4,
    name: 'Smartwatch FitTrack 2',
    description: 'Relógio inteligente com monitoramento cardíaco, GPS e resistência à água.',
    price: 899.0,
    category: 'Eletrônicos',
    stock: 20,
    image: 'https://picsum.photos/seed/smartwatch/600/400',
  },
  {
    id: 5,
    name: 'Cadeira Gamer ErgoFlex',
    description: 'Cadeira ergonômica com apoio lombar ajustável e reclínio de 180°.',
    price: 1299.9,
    category: 'Móveis',
    stock: 12,
    image: 'https://picsum.photos/seed/chair/600/400',
  },
  {
    id: 6,
    name: 'Teclado Mecânico RGB K87',
    description: 'Teclado mecânico com switches blue, iluminação RGB e teclas programáveis.',
    price: 349.9,
    category: 'Periféricos',
    stock: 25,
    image: 'https://picsum.photos/seed/keyboard/600/400',
  },
  {
    id: 7,
    name: 'Mouse Gamer PrecisionPro',
    description: 'Mouse com sensor de 16000 DPI, 8 botões programáveis e iluminação RGB.',
    price: 199.9,
    category: 'Periféricos',
    stock: 40,
    image: 'https://picsum.photos/seed/mouse/600/400',
  },
  {
    id: 8,
    name: 'Monitor UltraWide 34"',
    description: 'Monitor curvo ultrawide 34" QHD 144Hz, ideal para trabalho e games.',
    price: 2799.0,
    category: 'Eletrônicos',
    stock: 6,
    image: 'https://picsum.photos/seed/monitor/600/400',
  },
  {
    id: 9,
    name: 'Cafeteira Expresso Aroma',
    description: 'Cafeteira expresso com bomba de 15 bar e vaporizador de leite.',
    price: 749.9,
    category: 'Casa',
    stock: 18,
    image: 'https://picsum.photos/seed/coffee/600/400',
  },
  {
    id: 10,
    name: 'Mochila Urban Tech',
    description: 'Mochila antifurto com compartimento para notebook 15" e porta USB.',
    price: 229.9,
    category: 'Acessórios',
    stock: 35,
    image: 'https://picsum.photos/seed/backpack/600/400',
  },
  {
    id: 11,
    name: 'Caixa de Som BoomBox Go',
    description: 'Caixa de som portátil à prova d\'água com 24h de bateria.',
    price: 399.9,
    category: 'Áudio',
    stock: 22,
    image: 'https://picsum.photos/seed/speaker/600/400',
  },
  {
    id: 12,
    name: 'Webcam StreamCam HD',
    description: 'Webcam Full HD 1080p com microfone embutido e correção de luz.',
    price: 299.9,
    category: 'Periféricos',
    stock: 28,
    image: 'https://picsum.photos/seed/webcam/600/400',
  },
];
